import requests, re, json

countries = {
    "AFG": "Afghanistan",
    "ALB": "Albania",
    "ALG": "Algeria",
    "SAA": "American Samoa",
    "AND": "Andorra",
    "AGL": "Angola",
    "AGI": "Anguilla",
    "ATG": "Antigua & Barbuda",
    "UAE": "United Arab Emirates",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "ARU": "Aruba",
    "AUS": "Australia",
    "CHR": "Australia >> Christmas Island",
    "NFK": "Australia >> Norfolk",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "AZR": "Azores",
    "BAH": "Bahamas",
    "BHR": "Bahrain",
    "BNG": "Bangladesh",
    "BRB": "Barbados",
    "BLR": "Belarus",
    "BEL": "Belgium",
    "BLZ": "Belize",
    "BEN": "Benin",
    "BER": "Bermuda",
    "BHU": "Bhutan",
    "BOL": "Bolivia",
    "BOS": "Bosnia & Herzegovina",
    "BOT": "Botswana",
    "BRA": "Brazil",
    "BRU": "Brunei Darussalam",
    "BUL": "Bulgaria",
    "BFS": "Burkina Faso",
    "MMR": "Burma (Myanmar)",
    "BDI": "Burundi",
    "CBG": "Cambodia",
    "CAM": "Cameroon",
    "CAN": "Canada",
    "ICA": "Canary Islands",
    "CAV": "Cape Verde",
    "CYM": "Cayman Islands",
    "CAF": "Central African Rep.",
    "TCD": "Chad",
    "JER": "Channel Islands",
    "CHL": "Chile",
    "CHN": "China",
    "HKG": "China >> Hong Kong",
    "MAC": "China >> Macau",
    "TAI": "China >> Taiwan",
    "COL": "Colombia",
    "COM": "Comoros",
    "COG": "Congo",
    "ZAI": "Congo Dem. Rep.",
    "COK": "Cook Islands",
    "CRI": "Costa Rica",
    "CRO": "Croatia",
    "CUB": "Cuba",
    "CYP": "Cyprus",
    "TCH": "Czech Rep.",
    "DNK": "Denmark",
    "FRO": "Denmark >> Faroe Islands",
    "DJI": "Djibouti",
    "DMA": "Dominica",
    "DOM": "Dominican Rep.",
    "TIM": "East Timor",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "GNE": "Equatorial Guinea",
    "ERI": "Eritrea",
    "EST": "Estonia",
    "ETH": "Ethiopia",
    "FLK": "Falkland Islands",
    "FRO": "Faroe Islands",
    "FIJ": "Fiji",
    "FIN": "Finland",
    "FRA": "France",
    "GDL": "France >> Guadeloupe",
    "GIA": "France >> French Guiana",
    "MTN": "France >> Martinique",
    "MYT": "France >> Mayotte",
    "NCL": "France >> New Caledonia",
    "PFR": "France >> French Polynesia",
    "REU": "France >> Reunion",
    "SPM": "France >> St-Pierre & Miquelon",
    "GAB": "Gabon",
    "GAM": "Gambia",
    "GEO": "Georgia",
    "GER": "Germany",
    "GHA": "Ghana",
    "GIB": "Gibraltar",
    "GBR": "Great Britain",
    "MAN": "Great Britain >> Isle of Man",
    "JER": "Great Britain >> Jersey & Guernsey",
    "GRE": "Greece",
    "GRL": "Greenland",
    "GRD": "Grenada",
    "GUM": "Guam",
    "GTM": "Guatemala",
    "GIA": "Guiana (French)",
    "GUI": "Guinea",
    "GNB": "Guinea-Bissau",
    "GNE": "Guinea (Equat.)",
    "GUY": "Guyana",
    "HAI": "Haiti",
    "HAW": "Hawaii Islands",
    "HND": "Honduras",
    "HKG": "Hong Kong",
    "HUN": "Hungary",
    "ISL": "Iceland",
    "IND": "India",
    "IDN": "Indonesia",
    "IRQ": "Iraq",
    "IRN": "Iran",
    "IRL": "Ireland",
    "MAN": "Isle of Man",
    "ISR": "Israel",
    "ITA": "Italy",
    "CIV": "Ivory Coast",
    "JAM": "Jamaica",
    "JAP": "Japan",
    "JOR": "Jordan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KIR": "Kiribati",
    "KOR": "Korea",
    "KUW": "Kuwait",
    "KGZ": "Kyrgyzstan",
    "LAO": "Laos",
    "LAT": "Latvia",
    "LIB": "Lebanon",
    "LSO": "Lesotho",
    "LBR": "Liberia",
    "LBY": "Libya",
    "LIE": "Liechtenstein",
    "LIT": "Lithuania",
    "LUX": "Luxembourg",
    "MAC": "Macau",
    "MKD": "Macedonia",
    "MAD": "Madagascar",
    "MDR": "Madeira",
    "MWI": "Malawi",
    "MLS": "Malaysia",
    "MLD": "Maldives",
    "MLI": "Mali",
    "MLT": "Malta",
    "MRN": "Mariana Islands",
    "MHL": "Marshall Islands",
    "MRT": "Mauritania",
    "MRI": "Mauritius",
    "MEX": "Mexico",
    "MIC": "Micronesia",
    "MOL": "Moldova",
    "MCO": "Monaco",
    "MNG": "Mongolia",
    "MSR": "Montserrat",
    "MAR": "Morocco",
    "MOZ": "Mozambique",
    "NAM": "Namibia",
    "NRU": "Nauru",
    "NEP": "Nepal",
    "NED": "Netherlands",
    "ATN": "Netherlands Antilles",
    "NCL": "New Caledonia",
    "NZL": "New Zealand",
    "NIC": "Nicaragua",
    "NGR": "Niger",
    "NIU": "Niue",
    "NIG": "Nigeria",
    "MRN": "Northern Mariana Islands",
    "NOR": "Norway",
    "OMA": "Oman",
    "PAK": "Pakistan",
    "PLW": "Palau",
    "PAL": "Palestine",
    "PAN": "Panama",
    "PNG": "Papua New Guinea",
    "PAR": "Paraguay",
    "PER": "Peru",
    "PHL": "Philippines",
    "PIT": "Pitcairn",
    "POL": "Poland",
    "PFR": "Polynesia (French)",
    "PRT": "Portugal",
    "PRI": "Puerto Rico",
    "QAT": "Qatar",
    "REU": "Reunion",
    "ROM": "Romania",
    "RUS": "Russia",
    "RWA": "Rwanda",
    "SHE": "Saint Helena",
    "SKN": "Saint Kitts & Nevis",
    "SLU": "Saint Lucia",
    "SPM": "Saint Pierre & Miquelon",
    "VCT": "Saint Vincent & Grenadines",
    "SLV": "El Salvador",
    "SAM": "Samoa (Western)",
    "SMR": "San Marino",
    "STP": "Sao Tome & Principe",
    "SAU": "Saudi Arabia",
    "SEN": "Senegal",
    "SEY": "Seychelles",
    "SLE": "Sierra Leone",
    "SGP": "Singapore",
    "SLO": "Slovakia",
    "SVN": "Slovenia",
    "SLM": "Solomon",
    "SOM": "Somalia",
    "SAF": "South Africa",
    "ESP": "Spain",
    "SRI": "Sri Lanka",
    "SDN": "Sudan",
    "SUR": "Suriname",
    "SWA": "Swaziland",
    "SWE": "Sweden",
    "SUI": "Switzerland",
    "SYR": "Syria",
    "TJK": "Tajikistan",
    "TAN": "Tanzania",
    "THA": "Thailand",
    "TOG": "Togo",
    "TKL": "Tokelau",
    "TON": "Tonga",
    "TRI": "Trinidad & Tobago",
    "TUN": "Tunisia",
    "TUR": "Turkey",
    "TUR": "Turkmenistan",
    "TUV": "Tuvalu",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "URU": "Uruguay",
    "VUT": "Vanuatu",
    "VEN": "Venezuela",
    "VIR": "Virgin Islands",
    "VGB": "Virgin Islands (British)",
    "VIA": "Virgin Islands (U.S.)",
    "WLF": "Wallis & Futuna",
    "WSM": "Western Samoa",
    "YEM": "Yemen",
    "ZAR": "Zaire",
    "ZMB": "Zambia",
    "ZWE": "Zimbabwe"
}

data = []

def scrape(gender,country_code):
    url = f"https://top-names.info/names.php?S={gender}&P={country_code}"
    r = requests.get(url,headers={"user-agent":"Mozilla/5.0"})
    names = re.findall('<FONT class=t12>(.*?)</TD><TD></TD>',r.text)
    names_lower = []
    for name in names:
        names_lower.append(name.lower())
    return names_lower


for country in countries:
    temp_data = {
        country:{
            "country_name":countries[country],
            "M":[],
            "F":[]
        }
    }
    for gender in ['M','F']:
        temp_data[country][gender].append(scrape(gender,country))
    data.append(temp_data)
    
open('names.json','w').write(json.dumps(data,indent=2))